In [14]:
#
import numpy as np
a=[[2,5,np.nan],[4,5,9],[2,np.nan,89],[np.nan,44,22]]

In [15]:
#we are using scikit learn to do imputation
#install it by 
#pip3 install scikit_learn

#import sklearn

In [16]:
from sklearn.preprocessing import Imputer

In [17]:
#help(Imputer)

In [18]:
impobj=Imputer(missing_values=np.nan,strategy ='mean',axis=0)
# missing value is None

C:\Users\INDIA\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [19]:
impdata=impobj.fit(a)
#this step will fit the rules only to check data compatibility

In [20]:
#now to fix the missing values we need to transform data
a_improve=impdata.transform(a)

In [21]:
a_improve

array([[ 2.        ,  5.        , 40.        ],
       [ 4.        ,  5.        ,  9.        ],
       [ 2.        , 18.        , 89.        ],
       [ 2.66666667, 44.        , 22.        ]])

In [22]:
a

[[2, 5, nan], [4, 5, 9], [2, nan, 89], [nan, 44, 22]]

In [23]:
#another way to fix this issues

In [24]:
impobj1=Imputer(missing_values=np.nan,strategy ='mean',axis=0)

C:\Users\INDIA\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [25]:
newdata=impobj1.fit_transform(a)

In [26]:
newdata

array([[ 2.        ,  5.        , 40.        ],
       [ 4.        ,  5.        ,  9.        ],
       [ 2.        , 18.        , 89.        ],
       [ 2.66666667, 44.        , 22.        ]])

## new way of using imputation

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
#help(SimpleImputer)

In [29]:
newobj=SimpleImputer(missing_values=np.nan,strategy='mean')
#new version of imputation

In [30]:
newobj.fit_transform(a)

array([[ 2.        ,  5.        , 40.        ],
       [ 4.        ,  5.        ,  9.        ],
       [ 2.        , 18.        , 89.        ],
       [ 2.66666667, 44.        , 22.        ]])