In [1]:
#take the no of rows and columns from user then print all the zero matrix in which rows*columns are equal to the max of rows and columns
import numpy as np
rows=int(input("Enter the no of rows"))
columns=int(input("Enter the no of columns"))
if(rows>columns):
    max=rows
else:
    max=columns
print(np.zeros([rows,columns]))

for i in range(1,max+1):
    if((max % i == 0) and (max %(int(max/i))==0)):
        print(np.zeros([i,(max//i)]))


Enter the no of rows2
Enter the no of columns6
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
