In [1]:
#taking no of rows and columns from user and printing the matrix with random values
import numpy as np
rows=int(input("Enter number of rows"))  #taking input no of rows from user
columns=int(input("Enter number of columns"))  #taking input no of columns from user
matrix =np.random.random([rows,columns])
print("Matrix with random values is given as:\n",matrix)


Enter number of rows2
Enter number of columns3
Matrix with random values is given as:
 [[0.64345199 0.0956718  0.68286732]
 [0.99630215 0.10980111 0.93294976]]


In [2]:
#taking no of rows and columns from user and taking the elements of matrix from user as well
import numpy as np
rows=int(input("Enter no of rows"))
columns=int(input("Enter no of columns"))
print("Enter %d elements separated by ,(comma)"%(rows*columns))
#ar=np.array(rows,columns)
l=list(map(int,input().split(",")))

mat=np.array(l).reshape(rows,columns)
print(mat)

Enter no of rows2
Enter no of columns3
Enter 6 elements separated by ,(comma)
1,2,3,4,5,6
[[1 2 3]
 [4 5 6]]
