<a href="https://colab.research.google.com/github/NehaPatidar208/ML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#dir('np')

In [2]:
[i for i in dir(np) if 'arr' in i]

['array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'broadcast_arrays',
 'chararray',
 'compare_chararrays',
 'get_array_wrap',
 'ndarray',
 'numarray',
 'recarray']

In [0]:
a=np.array([2,3,9,7])

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([2, 3, 9, 7])

In [6]:
a.shape

(4,)

In [0]:
a1=np.array([[2,4],[3,6],[9,8],[7,11]])

In [8]:
type(a1)


numpy.ndarray

In [9]:
a1

array([[ 2,  4],
       [ 3,  6],
       [ 9,  8],
       [ 7, 11]])

In [10]:
a1.shape

(4, 2)

In [0]:
a2=np.array([[2,4,5],[3,6,7],[9,8,2],[7,11,4]])

In [12]:
a2

array([[ 2,  4,  5],
       [ 3,  6,  7],
       [ 9,  8,  2],
       [ 7, 11,  4]])

In [13]:
a2.shape

(4, 3)

In [14]:
a1

array([[ 2,  4],
       [ 3,  6],
       [ 9,  8],
       [ 7, 11]])

In [15]:
a1[0]

array([2, 4])

In [16]:
a1[0][0]

2

In [17]:
a2

array([[ 2,  4,  5],
       [ 3,  6,  7],
       [ 9,  8,  2],
       [ 7, 11,  4]])

In [18]:
a2[2][2]

2

In [0]:
x=a2[0:2]

In [20]:
x

array([[2, 4, 5],
       [3, 6, 7]])

In [21]:
x[1:3]

array([[3, 6, 7]])

In [22]:
a2[1,1]

6

In [23]:
a2[0:2][0:2]

array([[2, 4, 5],
       [3, 6, 7]])

In [24]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
x=np.full((4,3),2)

In [0]:
y=np.full((4,3),5)

In [28]:
x+2

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [29]:
x*3

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [0]:
z=x*6

In [31]:
x+y

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [32]:
x/4

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [33]:
np.add(x,y)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])